{% set name = "myst-parser" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45fe6407d49221bdcc10d5000f4f2f3ff2614af268dd33f351f7230d6059f0d8

build:
  number: 0
  entry_points:
    - myst-benchmark = myst_parser.cli.benchmark:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils >=0.15,<0.18
    - markdown-it-py >=1.0.0,<3.0.0
    - mdit-py-plugins >=0.3.0,<1
    - jinja2
    - python >=3.6
    - pyyaml
    - sphinx >=3.1,<5
    - typing-extensions

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - myst_parser
    - myst_parser.cli

about:
  home: https://github.com/ExecutableBookProject/MyST-Parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extended commonmark compliant parser, with bridges to docutils & sphinx.
  doc_url: https://myst-parser.readthedocs.io

extra:
  recipe-maintainers:
    - dopplershift
    - choldgraf
