{% set name = "myst-parser" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 739a4d96773a8e55a2cacd3941ce46a446ee23dcd6b37e06f73f551ad7821d86

build:
  number: 0
  entry_points:
    - myst-benchmark = myst_parser.cli.benchmark:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3.4,<4
  run:
    - docutils >=0.15,<0.19
    - markdown-it-py >=1.0.0,<3.0.0
    - mdit-py-plugins >=0.3.0,<1
    - jinja2
    - python >=3.7
    - pyyaml
    - sphinx >=4,<6
    - typing-extensions

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - myst_parser
    - myst_parser.cli

about:
  home: https://github.com/ExecutableBookProject/MyST-Parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extended commonmark compliant parser, with bridges to docutils & sphinx.
  doc_url: https://myst-parser.readthedocs.io

extra:
  recipe-maintainers:
    - dopplershift
    - choldgraf
