{% set name = "myst-parser" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5281f72cc37742b5b753f2bbfdb8f970ae98b01f09cbae192a0dd2560cd70974

build:
  number: 0
  entry_points:
    - myst-benchmark = myst_parser.cli.benchmark:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils >=0.15
    - markdown-it-py ~=0.6.0
    - mdit-py-plugins ~=0.2.4
    - jinja2
    - python >=3.6
    - pyyaml
    - sphinx >=2,<4

test:
  imports:
    - myst_parser
    - myst_parser.cli

about:
  home: https://github.com/ExecutableBookProject/MyST-Parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extended commonmark compliant parser, with bridges to docutils & sphinx.
  doc_url: https://myst-parser.readthedocs.io

extra:
  recipe-maintainers:
    - chrisjsewell
    - choldgraf
